Subscribe = "ベンソン級駆逐艦ラフィー、命令を待っている……"
Unsubscribe = "了解、命令が来るまで寝る……"
NotSubscribed = "まだ通知が登録されてなかったよ……"
BringIssue = "指揮官に、メール……"
BringPR = "コードレビュー終わったら、一緒にワイン飲もう……"
NothingToBring = "任務は無いみたい……"
EnumIssue = "まだ任務がありそう……"
EnumPR = "うん……そこそこ……？"
InvalidToken = "トークンがおかしいみたい……"

Failure = [
  "ラフィー、よくわからない……",
  "今日、何かしないといけないこと……覚えていない……",
  "ラフィーは指揮官が悪いなんて思ってない。うん、思ってない…(ツンツン"
]

Flavor = [
  "Zzz……",
  "指揮官、一緒にねんねする？",
  "うん……二度寝しよう……",
  "指揮官、疲れた？",
  "指揮官、元気？"
]

BlackPattern = "[こっぽんコッポンHKTN]"
CallPattern = "寝る|寝ます|ねる|ねます|oti|ochi|落ち|おち|疲れた|ラフィ|らふぃ"
