Subscribe = "ベンソン級駆逐艦ラフィー、命令を待っている……"
Unsubscribe = "わたしがこの体じゃなくなっても、まだ見てくれるの……？"
BringIssue = "指揮官に、メール……"
BringPR = "コードレビュー終わったら、一緒にワイン飲もう……"
EnumIssue = "まだ任務がありそう……"
EnumPR = "うん……そこそこ……？"

Flavor = [
  "Zzz……",
  "指揮官、一緒にねんねする？",
  "うん……二度寝しよう……",
  "指揮官、疲れた？",
  "指揮官、元気？"
]
