name: Lints

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.0.0, 1.0.1, 1.0.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno v${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint
        run: deno fmt --check
