name: Tests

on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.0.0, 1.0.1, 1.0.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno v${{ matrix.deno-version }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Build
        run: deno run --reload main.ts
      - name: Test
        run: deno test --allow-none
